version: "3"

services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:good
    depends_on:
      - wordpress
    networks:
      - docker-network
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
    image: wordpress:good
    depends_on:
      - mariadb
    networks:
      - docker-network
    #ports:
      #- "9000:9000"
    volumes:
      - wordpress_vol:/var/www/wordpress
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mariadb:good
    networks:
      - docker-network
    #ports:
      #- "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  docker-network: {}

volumes:
  db_vol: 
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/db_vol
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress_vol
      o: bind

